### ISSUE TITLE
About a problem for installation of the ISPAQ on the MACOSX

### ISSUE THREAD

**Issue by YANG-JAEYEOL** [EarthScope/ispaq#10]
Dear Sir,

I am trying to install the ispaq package. But I have faced problem as below.

Could you please let me know how to solve this problem?

Thank you in advance.

(ispaq) jaeyeol-ui-MacBook-Pro:ispaq jaeyeolyang$ export MACOSX_DEPLOYMENT_TARGET=10.9
(ispaq) jaeyeol-ui-MacBook-Pro:ispaq jaeyeolyang$ ./run_ispaq.py -I
2022-02-12 21:09:16 - INFO - Running ISPAQ version 3.0.0 on Sat Feb 12 21:09:16 2022
Traceback (most recent call last):
  File "./run_ispaq.py", line 15, in <module>
    main()
  File "/Users/jaeyeolyang/ispaq/ispaq/ispaq.py", line 149, in main
    import obspy
  File "/Users/jaeyeolyang/anaconda3/envs/ispaq/lib/python3.8/site-packages/obspy/__init__.py", line 39, in <module>
    from obspy.core.utcdatetime import UTCDateTime  # NOQA
  File "/Users/jaeyeolyang/anaconda3/envs/ispaq/lib/python3.8/site-packages/obspy/core/__init__.py", line 124, in <module>
    from obspy.core.utcdatetime import UTCDateTime  # NOQA
  File "/Users/jaeyeolyang/anaconda3/envs/ispaq/lib/python3.8/site-packages/obspy/core/utcdatetime.py", line 27, in <module>
    from obspy.core.util.deprecation_helpers import ObsPyDeprecationWarning
  File "/Users/jaeyeolyang/anaconda3/envs/ispaq/lib/python3.8/site-packages/obspy/core/util/__init__.py", line 27, in <module>
    from obspy.core.util.base import (ALL_MODULES, DEFAULT_MODULES,
  File "/Users/jaeyeolyang/anaconda3/envs/ispaq/lib/python3.8/site-packages/obspy/core/util/base.py", line 36, in <module>
    from obspy.core.util.misc import to_int_or_zero, buffered_load_entry_point
  File "/Users/jaeyeolyang/anaconda3/envs/ispaq/lib/python3.8/site-packages/obspy/core/util/misc.py", line 214, in <module>
    loadtxt(np.array([0]), ndmin=1)
  File "/Users/jaeyeolyang/anaconda3/envs/ispaq/lib/python3.8/site-packages/numpy/lib/npyio.py", line 1086, in loadtxt
    ncols = len(usecols or split_line(first_line))
  File "/Users/jaeyeolyang/anaconda3/envs/ispaq/lib/python3.8/site-packages/numpy/lib/npyio.py", line 977, in split_line
    line = line.split(comment, 1)[0]
AttributeError: 'numpy.int64' object has no attribute 'split'

**Comment by xiaot1228** [comment]
你好请问问题解决了吗，我也碰到类似问题但是是linux下，好像和系统无关

**Comment by gillian-iris** [comment]
Thank you for this problem report. I have recreated this result, and the issue is that the latest numpy version 1.22 is incompatible with ISPAQ. A solution is to run the following:

conda deactivate (if you are in the ispaq environment)
conda env remove --name ispaq
conda create --name ispaq -c conda-forge python=3.8 obspy=1.2.2 numpy=1.21.4
conda activate ispaq
conda install -c conda-forge --file ispaq-conda-install.txt

and then continue with the installation.

**Comment by YANG-JAEYEOL** [comment]
Thanks.
